### ISSUE TITLE
[Feature] GUI 美化？

### ISSUE THREAD

**Issue by KasumiNova** [BalloonUpdate/JarClient#5]
介于原版的 Java Swing 界面观感稀烂，是否可以尝试添加一些界面库？
[如此类界面](https://www.formdev.com/flatlaf/)

**Comment by asforest** [comment]
之前开发重心一直是放在了核心功能上，对界面的要求就是能凑合用就可以。刚试玩了一下FlatLaf感觉很不错，可以添加作为默认的界面主题。（好像代码改动也挺少的，工作量不大）

已经加入到开发日程里，具体的开发进度可以关注一下GItHub组织的Projects界面

**Comment by asforest** [comment]
close #6
